export const GET_ALL_BOOKS_REQUEST = 'GET_PRODUCTS_ALL';
export const ALL_BOOKS_RECEIVED_RESPONSE ='ALL_BOOKS_RECEIVED';
export const ERROR_RESPONSE = 'ERROR';
export const CLEAR_ALL_BOOKS = 'CLEAR_ALL_BOOKS';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const ALREADY_IN_WISHLIST = "ALREADY_IN_WISHLIST";
export const REMOVE_ALREADY_IN_WISHLIST = "REMOVE_ALREADY_IN_WISHLIST";

export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const CHANGE_MULTIPLIER = 'CHANGE_MULTIPLIER';